"""adds Goal model

Revision ID: 370819dc222e
Revises: dbc43b511dd3
Create Date: 2024-11-03 09:09:39.790517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370819dc222e'
down_revision = 'dbc43b511dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
